#ifndef _GAME_SPRITES__H
#define _GAME_SPRITES__H

#include <inttypes.h>

#include "game_structs.h"

#define NUM_SPRITE_TYPES 54
#define SPRITE_TYPE_EMPTY 0
// 1 intentionally skipped
#define SPRITE_TYPE_ORC_STAND_RIGHT 2
#define SPRITE_TYPE_ORC_WALK_RIGHT_1 3
#define SPRITE_TYPE_ORC_WALK_RIGHT_2 4
#define SPRITE_TYPE_ORC_WALK_RIGHT_3 5
#define SPRITE_TYPE_ORC_WALK_RIGHT_4 6
#define SPRITE_TYPE_ORC_WALK_RIGHT_5 7
#define SPRITE_TYPE_ORC_WALK_RIGHT_6 8
#define SPRITE_TYPE_ORC_WALK_RIGHT_7 9

#define SPRITE_TYPE_MUSHROOM_STAND_RIGHT 10
#define SPRITE_TYPE_MUSHROOM_WALK_RIGHT_1 11
#define SPRITE_TYPE_MUSHROOM_WALK_RIGHT_2 12
#define SPRITE_TYPE_MUSHROOM_WALK_RIGHT_3 13
#define SPRITE_TYPE_MUSHROOM_WALK_RIGHT_4 14
#define SPRITE_TYPE_MUSHROOM_WALK_RIGHT_5 15
#define SPRITE_TYPE_MUSHROOM_WALK_RIGHT_6 16
#define SPRITE_TYPE_MUSHROOM_WALK_RIGHT_7 17

#define SPRITE_TYPE_CAT_STAND_RIGHT 18
#define SPRITE_TYPE_CAT_WALK_RIGHT_1 19
#define SPRITE_TYPE_CAT_WALK_RIGHT_2 20
#define SPRITE_TYPE_CAT_WALK_RIGHT_3 21
#define SPRITE_TYPE_CAT_WALK_RIGHT_4 22
#define SPRITE_TYPE_CAT_WALK_RIGHT_5 23

#define DIRECTION_MASK_LEFT 0b00000001
#define DIRECTION_MASK_RIGHT 0b00000010
#define DIRECTION_MASK_UP 0b00000100
#define DIRECTION_MASK_DOWN 0b00001000

#define SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES 24
#define SPRITE_TYPE_GROUND_OPEN_LEFT 1 + SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES
#define SPRITE_TYPE_GROUND_OPEN_RIGHT 2 + SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES
#define SPRITE_TYPE_GROUND_OPEN_LEFT_RIGHT 3 + SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES
#define SPRITE_TYPE_GROUND_OPEN_UP 4 + SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES
#define SPRITE_TYPE_GROUND_OPEN_LEFT_UP 5 + SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES
#define SPRITE_TYPE_GROUND_OPEN_RIGHT_UP 6 + SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES
#define SPRITE_TYPE_GROUND_OPEN_LEFT_RIGHT_UP 7 + SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES
#define SPRITE_TYPE_GROUND_OPEN_DOWN 8 + SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES
#define SPRITE_TYPE_GROUND_OPEN_LEFT_DOWN 9 + SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES
#define SPRITE_TYPE_GROUND_OPEN_RIGHT_DOWN 10 + SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES
#define SPRITE_TYPE_GROUND_OPEN_LEFT_RIGHT_DOWN 11 + SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES
#define SPRITE_TYPE_GROUND_OPEN_UP_DOWN 12 + SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES
#define SPRITE_TYPE_GROUND_OPEN_LEFT_UP_DOWN 13 + SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES
#define SPRITE_TYPE_GROUND_OPEN_RIGHT_UP_DOWN 14 + SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES
#define SPRITE_TYPE_GROUND_OPEN_LEFT_RIGHT_UP_DOWN 15 + SPRITE_TYPE_GROUND_BLOCKED_ALL_SIDES

#define SPRITE_TYPE_LADDER 40

#define SPRITE_TYPE_TOILET 41

#define SPRITE_TYPE_MUSHROOM_CLIMB_1 42
#define SPRITE_TYPE_MUSHROOM_CLIMB_2 43
#define SPRITE_TYPE_MUSHROOM_CLIMB_3 44
#define SPRITE_TYPE_MUSHROOM_CLIMB_4 45
#define SPRITE_TYPE_MUSHROOM_CLIMB_5 46
#define SPRITE_TYPE_MUSHROOM_CLIMB_6 47
#define SPRITE_TYPE_MUSHROOM_CLIMB_7 48
#define SPRITE_TYPE_MUSHROOM_CLIMB_8 49
#define SPRITE_TYPE_MUSHROOM_CLIMB_9 50
#define SPRITE_TYPE_MUSHROOM_CLIMB_10 51
#define SPRITE_TYPE_MUSHROOM_CLIMB_11 52
#define SPRITE_TYPE_MUSHROOM_CLIMB_12 53


// Remember to update NUM_SPRITE_TYPES


void initialize_sprites(struct ImageInfo* image_array, struct Sprite* r_sprite_array);

#endif  // _GAME_SPRITES__H