#ifndef _GAME_PATHS__H
#define _GAME_PATHS__H

#define GAME_PATH__ROOT_PATH "/Users/matthew.enss/personal/c/"
// I think this is for my old work laptop that I now own, with the data team sticker on it #define GAME_PATH__ROOT_PATH "/Users/matthewenss/c/"

#define GAME_PATH__IMAGE_PATH_SOLIDS_1 "pixels-sdl-assets/used-in-game/Tileset.bmp"
#define GAME_PATH__IMAGE_PATH_SOLIDS_2 "pixels-sdl-assets/used-in-game/tileset-expanded5.bmp"
#define GAME_PATH__IMAGE_PATH_ORC_1_RIGHT "pixels-sdl-assets/used-in-game/Orc.bmp"
#define GAME_PATH__IMAGE_PATH_MUSHROOM_RIGHT "pixels-sdl-assets/used-in-game/mushroom_spritesheet3.bmp"
#define GAME_PATH__IMAGE_PATH_CAT_RIGHT "pixels-sdl-assets/used-in-game/cato-walk.bmp"
#define GAME_PATH__IMAGE_PATH_TOILET "pixels-sdl-assets/used-in-game/toilet.bmp"
#define GAME_PATH__IMAGE_PATH_WORM "pixels-sdl-assets/used-in-game/worm_spritesheet.bmp"
#define GAME_PATH_CATCH__IMAGE_PATH_ROWAN_CATCH_CUTOUT_SCALED "assets-rowan/rowan-catch-cutout-scaled.bmp"
#define GAME_PATH_CATCH__IMAGE_PATH_ROWAN_CATCH_CUTOUT_SCALED_WHITE_RECTANGLE "assets-rowan/rowan-catch-cutout-scaled-white-rectangle.bmp"
#define GAME_PATH_CATCH__IMAGE_PATH_HAMBURGER_CUTOUT_SCALED "assets-rowan/hamburger-cutout-scaled.bmp"
#define GAME_PATH_CATCH__IMAGE_PATH_HAMBURGER_CUTOUT_SCALED_WHITE_RECTANGLE "assets-rowan/hamburger-cutout-scaled-white-rectangle.bmp"

#define GAME_PATH__IMAGE_PATH_SOLIDS_1_FULL GAME_PATH__ROOT_PATH GAME_PATH__IMAGE_PATH_SOLIDS_1
#define GAME_PATH__IMAGE_PATH_SOLIDS_2_FULL GAME_PATH__ROOT_PATH GAME_PATH__IMAGE_PATH_SOLIDS_2
#define GAME_PATH__IMAGE_PATH_ORC_1_RIGHT_FULL GAME_PATH__ROOT_PATH GAME_PATH__IMAGE_PATH_ORC_1_RIGHT
#define GAME_PATH__IMAGE_PATH_MUSHROOM_RIGHT_FULL GAME_PATH__ROOT_PATH GAME_PATH__IMAGE_PATH_MUSHROOM_RIGHT
#define GAME_PATH__IMAGE_PATH_CAT_RIGHT_FULL GAME_PATH__ROOT_PATH GAME_PATH__IMAGE_PATH_CAT_RIGHT
#define GAME_PATH__IMAGE_PATH_TOILET_FULL GAME_PATH__ROOT_PATH GAME_PATH__IMAGE_PATH_TOILET
#define GAME_PATH__IMAGE_PATH_WORM_FULL GAME_PATH__ROOT_PATH GAME_PATH__IMAGE_PATH_WORM

#define GAME_PATH_CATCH__IMAGE_PATH_ROWAN_CATCH_CUTOUT_SCALED_FULL GAME_PATH__ROOT_PATH GAME_PATH_CATCH__IMAGE_PATH_ROWAN_CATCH_CUTOUT_SCALED
// #define GAME_PATH_CATCH__IMAGE_PATH_ROWAN_CATCH_CUTOUT_SCALED_FULL GAME_PATH__ROOT_PATH GAME_PATH_CATCH__IMAGE_PATH_ROWAN_CATCH_CUTOUT_SCALED_WHITE_RECTANGLE
#define GAME_PATH_CATCH__IMAGE_PATH_HAMBURGER_CUTOUT_SCALED_FULL GAME_PATH__ROOT_PATH GAME_PATH_CATCH__IMAGE_PATH_HAMBURGER_CUTOUT_SCALED
// #define GAME_PATH_CATCH__IMAGE_PATH_HAMBURGER_CUTOUT_SCALED_FULL GAME_PATH__ROOT_PATH GAME_PATH_CATCH__IMAGE_PATH_ROWAN_CATCH_CUTOUT_SCALED_WHITE_RECTANGLE


#define GAME_PATH__TEXT_PATH_WORLD_RULES "assets-rowan/world-rules.cfg"

#define GAME_PATH__TEXT_PATH_WORLD_RULES_FULL GAME_PATH__ROOT_PATH GAME_PATH__TEXT_PATH_WORLD_RULES

#define GAME_PATH__LEVEL_FILES "pixels-sdl-assets/used-in-game/level-files/"
#define GAME_PATH__LEVEL_FILES__EDITOR_FILES GAME_PATH__LEVEL_FILES "editor-level-{slot}.lvl"
#define GAME_PATH__LEVEL_FILES__EDITOR_FILES__FULL GAME_PATH__ROOT_PATH GAME_PATH__LEVEL_FILES__EDITOR_FILES

#endif  // _GAME_PATHS__H
